import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FirstPanel from './components/main-page/FirstPanel'
import FirstPanelStripes from './components/main-page/FirstPanelStripes'
import Footer from './components/Footer'
import Form from './components/main-page/Form'
import Front from './components/main-page/Front'
import Navigation from './Navigation'
import SecondPanel from './components/main-page/SecondPanel'
import SecondPanelStripes from './components/main-page/SecondPanelStripes'
import ThirdPanel from './components/main-page/ThirdPanel'
import ThirdPanelStripes from './components/main-page/ThirdPanelStripes'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Front />
      <FirstPanelStripes />
      <FirstPanel />
      <SecondPanelStripes />
      <SecondPanel />
      <ThirdPanelStripes />
      <ThirdPanel />
      <Form />
      <Footer />
    </>
 
  )
}
